export const userConstants = {
    LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
    LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
    LOGIN_FAIURE: "USERS_LOGIN_FAILURE",

    GET_ALL_REQUEST: "USERS_GET_ALL_REQUEST",
    GET_ALL_SUCCESS: "USERS_GET_ALL_SUCCESS",
    GET_ALL_FAILIRE: "USERS_GET_ALL_FAILURE",

    LOGOUT: "USERS_LOGOUT"
};